Modernise the header to match the main site
My "gem" doesn't have "gh-pages", nor do I have jekyll to test it seems;
so I'm just going to be wholly irresponsible and see if I can push this...

$ gem install gh-pages
ERROR:  Could not find a valid gem 'gh-pages' (>= 0) in any repository
ERROR:  Possible alternatives: ckpages, gh_badges, pages